-- Trigger node script, autogenerated by Tomb Editor 1.5.2
-- Do not modify this file manually.

LevelFuncs.__0000_Test_OnEnter = function(activator)
	if (LevelFuncs.KeyIsHeld(6)) then
		LevelFuncs.FlashScreen(Color(148,200,26), 1)
		LevelFuncs.EnableMoveable("flame_emitter2_212")
		LevelFuncs.PlayAudioTrack("102_AMB_Underwater_L", 0)
	else
		LevelFuncs.FlashScreen(Color(224,114,48), 2)
		LevelFuncs.DisableMoveable("flame_emitter2_212")
	end
end

LevelFuncs.__0001_TestByName_OnEnter = function(activator)
	if (LevelFuncs.TestMoveableName(activator:GetName(), "kurtis")) then
		LevelFuncs.PlaySoundAroundMoveable("LARA", 36)
		LevelFuncs.ExplodeMoveable(activator:GetName())
		LevelFuncs.FlashScreen(Color(0,255,0), 1)
	else
		LevelFuncs.PlaySoundAroundMoveable("LARA", 30)
		LevelFuncs.ShatterMoveable(activator:GetName())
		LevelFuncs.FlashScreen(Color(255,0,0), 1)
	end
end

